//! Generate the supported upstream browser contract from compiled Rust TS derives.
//! Non-migrated browser/fork models live in proto/src/legacy, outside this gate.

use anyhow::{Context, Result, bail};
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::ExitCode,
};
use ts_rs::{Config, TS};

const HEADER: &str = "// DO NOT EDIT — generated from upstream Rust by `cargo run -p wiregen` (check: `-- --check`).\n";
const TS_HEADER: &str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";
type Snapshot = BTreeMap<String, Vec<u8>>;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn export(cfg: &Config) -> Result<()> {
    macro_rules! types {
        ($($ty:ty),* $(,)?) => { $(<$ty as TS>::export_all(cfg).context(stringify!($ty))?;)* };
    }
    // Core identity, registry watches, chat creation/configuration and commands.
    // export_all also walks their named dependencies.
    types!(
        zeron_proto::EngineInfo,
        zeron_proto::SidebarPreferencesState,
        zeron_proto::SidebarPreferences,
        zeron_proto::SidebarSection,
        zeron_proto::SidebarPinChange,
        zeron_proto::SidebarSectionChange,
        zeron_proto::WorkspaceScope,
        zeron_proto::Device,
        zeron_proto::Space,
        zeron_proto::Chat,
        zeron_proto::ChatIndicator,
        zeron_proto::Session,
        zeron_proto::SessionStatus,
        zeron_proto::Model,
        zeron_proto::SteeringMode,
        zeron_proto::SlashCommand,
        zeron_proto::RunRequest,
        zeron_proto::AgentEvent,
        zeron_proto::ContextUsage,
        zeron_doc::SessionCommandEntry,
        zeron_doc::SessionCommandKind,
        zeron_doc::SessionCommandStatus,
        zeron_doc::SessionCommandPayload,
        zeron_doc::SessionMessageEntry,
        zeron_doc::SessionTail,
        zeron_doc::TranscriptUpdate,
        zeron_doc::TranscriptFrame,
        zeron_doc::QueuedMessage,
        zeron_update::UpdateStatus,
    );
    Ok(())
}

/// Inventory the real RPC constants via Rust's AST, never browser string copies.
/// Constants alone do not prove dispatch: the real-engine tests exercise the core.
fn methods(source: &str) -> Result<BTreeMap<String, String>> {
    let file = syn::parse_file(source).context("parse upstream RPC source")?;
    let module = file
        .items
        .iter()
        .find_map(|item| match item {
            syn::Item::Mod(module) if module.ident == "methods" => Some(module),
            _ => None,
        })
        .context("RPC methods module is missing")?;
    let (_, items) = module
        .content
        .as_ref()
        .context("methods must be an inline module")?;
    let mut methods = BTreeMap::new();
    for item in items {
        let syn::Item::Const(item) = item else {
            continue;
        };
        let syn::Expr::Lit(expr) = item.expr.as_ref() else {
            bail!(
                "RPC method {} is no longer a literal; update the inventory generator",
                item.ident
            );
        };
        let syn::Lit::Str(value) = &expr.lit else {
            bail!("RPC method {} is not a string", item.ident);
        };
        methods.insert(item.ident.to_string(), value.value());
    }
    Ok(methods)
}

fn method_inventory(source: &str) -> Result<String> {
    let methods = methods(source)?;
    let mut out = HEADER.to_owned();
    out.push_str("\n/** Declared by crates/rpc/src/lib.rs; advanced behavior is not implied. */\nexport const UPSTREAM_METHODS = {\n");
    for (name, value) in &methods {
        out.push_str(&format!("  {name}: {value:?},\n"));
    }
    out.push_str("} as const;\n\nexport type UpstreamMethod = (typeof UPSTREAM_METHODS)[keyof typeof UPSTREAM_METHODS];\n");
    out.push_str("\n/** Required core calls exercised against the engine, not advanced feature claims. */\nexport const CORE_METHODS = [\n");
    for name in [
        "ENGINE_INFO",
        "LOCAL_DEVICE",
        "WATCH_DEVICES",
        "WATCH_SPACES",
        "WATCH_CHATS",
        "WATCH_SESSIONS",
        "MUTATE",
        "QUEUE_COMMAND",
        "WATCH_DOC_MESSAGES",
        "WATCH_QUEUE",
        "LIST_HARNESSES",
        "LIST_MODELS",
    ] {
        if !methods.contains_key(name) {
            bail!("required upstream core method {name} is missing");
        }
        out.push_str(&format!("  UPSTREAM_METHODS.{name},\n"));
    }
    out.push_str("] as const;\n\n/** Retired fork-only calls, retained for negative contract checks, not supported upstream. */\nexport const UNSUPPORTED_LEGACY_METHODS = [\n  \"PrepareSpacePath\",\n  \"SetSidebarPins\",\n  \"SetSidebarSections\",\n  \"WatchSidebarState\",\n] as const;\n");
    Ok(out)
}

fn constants() -> String {
    let mut out = HEADER.to_owned();
    for (name, value) in [
        (
            "COMPOSER_REFERENCES_V1",
            zeron_proto::capabilities::COMPOSER_REFERENCES_V1,
        ),
        (
            "MESSAGE_QUEUE_V1",
            zeron_proto::capabilities::MESSAGE_QUEUE_V1,
        ),
        (
            "MESSAGE_QUEUE_ACTIONS_V1",
            zeron_proto::capabilities::MESSAGE_QUEUE_ACTIONS_V1,
        ),
        (
            "MESSAGE_QUEUE_ATTACHMENTS_V1",
            zeron_proto::capabilities::MESSAGE_QUEUE_ATTACHMENTS_V1,
        ),
        (
            "MESSAGE_QUEUE_CLEAN_ATTACHMENT_TEXT_V1",
            zeron_proto::capabilities::MESSAGE_QUEUE_CLEAN_ATTACHMENT_TEXT_V1,
        ),
        (
            "MESSAGE_QUEUE_EDIT_LEASE_V1",
            zeron_proto::capabilities::MESSAGE_QUEUE_EDIT_LEASE_V1,
        ),
        ("LIVE_PLAN_TOOL_ID", zeron_proto::LIVE_PLAN_TOOL_ID),
    ] {
        out.push_str(&format!("export const {name} = {value:?};\n"));
    }
    for (name, values) in [
        ("CAPABILITIES_CURRENT", zeron_proto::capabilities::CURRENT),
        ("SUBAGENT_MODEL_KEYS", &zeron_proto::SUBAGENT_MODEL_KEYS[..]),
        ("SUBAGENT_INPUT_KEEP", &zeron_proto::SUBAGENT_INPUT_KEEP[..]),
    ] {
        out.push_str(&format!(
            "export const {name}: readonly string[] = {values:?};\n"
        ));
    }
    for (name, value) in [
        (
            "PREVIEW_PROXY_PORT",
            zeron_proto::PREVIEW_PROXY_PORT as usize,
        ),
        (
            "MAX_WORKSPACE_IMAGE_BYTES",
            zeron_proto::MAX_WORKSPACE_IMAGE_BYTES,
        ),
        (
            "WORKSPACE_IMAGE_CHUNK_BYTES",
            zeron_proto::WORKSPACE_IMAGE_CHUNK_BYTES,
        ),
    ] {
        out.push_str(&format!("export const {name} = {value};\n"));
    }
    out
}

fn snapshot(dir: &Path) -> Result<Snapshot> {
    let mut files = Snapshot::new();
    if !dir.exists() {
        return Ok(files);
    }
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if !path.is_file() {
            bail!(
                "unexpected directory in generated output: {}",
                path.display()
            );
        }
        let name = path
            .file_name()
            .context("missing file name")?
            .to_str()
            .context("non-UTF8 file name")?
            .to_owned();
        files.insert(name, fs::read(path)?);
    }
    Ok(files)
}

fn generate(dir: &Path, rpc_source: &str) -> Result<Snapshot> {
    let cfg = Config::new()
        .with_out_dir(dir)
        .with_large_int("number")
        .with_import_extension(None::<String>);
    export(&cfg)?;
    let mut files = Snapshot::new();
    for (name, bytes) in snapshot(dir)? {
        let text = String::from_utf8(bytes)?;
        let body = text
            .strip_prefix(TS_HEADER)
            .context("unexpected ts-rs output header")?
            .trim_start_matches(['\r', '\n']);
        let body: String = body
            .lines()
            .map(|line| format!("{}\n", line.trim_end()))
            .collect();
        files.insert(name, format!("{HEADER}\n{body}").into_bytes());
    }
    files.insert("constants.ts".into(), constants().into_bytes());
    files.insert(
        "methods.ts".into(),
        method_inventory(rpc_source)?.into_bytes(),
    );
    let mut index = format!("{HEADER}\n");
    for name in files.keys() {
        index.push_str(&format!(
            "export * from \"./{}\";\n",
            name.trim_end_matches(".ts")
        ));
    }
    files.insert("index.ts".into(), index.into_bytes());
    Ok(files)
}

fn differences(expected: &Snapshot, actual: &Snapshot) -> Vec<String> {
    let mut diffs = Vec::new();
    for (name, bytes) in expected {
        match actual.get(name) {
            None => diffs.push(format!("{name}: missing")),
            Some(other) if other != bytes => diffs.push(format!("{name}: differs")),
            _ => (),
        }
    }
    for name in actual.keys().filter(|name| !expected.contains_key(*name)) {
        diffs.push(format!("{name}: no longer generated"));
    }
    diffs
}

fn run() -> Result<bool> {
    let mut check = false;
    let mut output = root().join("web/packages/proto/src/generated");
    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--check" => check = true,
            "--out-dir" => {
                output = PathBuf::from(args.next().context("--out-dir requires a path")?)
            }
            _ => bail!("usage: wiregen [--check] [--out-dir PATH]"),
        }
    }
    let scratch = root().join("target/wiregen");
    fs::create_dir_all(&scratch)?;
    let temp = tempfile::tempdir_in(scratch)?;
    let rpc = fs::read_to_string(root().join("crates/rpc/src/lib.rs"))?;
    let expected = generate(temp.path(), &rpc)?;
    let actual = snapshot(&output)?;
    let diff = differences(&expected, &actual);
    if check {
        if diff.is_empty() {
            println!("wire contracts are fresh ({} files)", expected.len());
            return Ok(true);
        }
        eprintln!(
            "wire contracts are stale; run `cargo run -p wiregen`:\n  {}",
            diff.join("\n  ")
        );
        return Ok(false);
    }
    // Remove only obsolete outputs bearing this generator's provenance.
    // Handwritten/fork models require an explicit migration, not directory cleanup.
    let obsolete: Vec<_> = actual
        .keys()
        .filter(|name| !expected.contains_key(*name))
        .collect();
    for name in &obsolete {
        if !actual[*name].starts_with(HEADER.as_bytes()) {
            bail!("{name} is not upstream-generated; move it to src/legacy before regenerating");
        }
    }
    for name in obsolete {
        fs::remove_file(output.join(name))?;
    }
    fs::create_dir_all(&output)?;
    for (name, bytes) in &expected {
        fs::write(output.join(name), bytes)?;
    }
    println!(
        "generated {} upstream contract files in {}",
        expected.len(),
        output.display()
    );
    Ok(true)
}

fn main() -> ExitCode {
    match run() {
        Ok(true) => ExitCode::SUCCESS,
        Ok(false) => ExitCode::FAILURE,
        Err(error) => {
            eprintln!("wiregen: {error:#}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn method_schema_change_is_visible_and_missing_core_is_rejected() {
        let source = fs::read_to_string(root().join("crates/rpc/src/lib.rs")).unwrap();
        let scratch = root().join("target/wiregen-tests");
        fs::create_dir_all(&scratch).unwrap();
        let temp = tempfile::tempdir_in(scratch).unwrap();
        let original = generate(&temp.path().join("original"), &source).unwrap();
        let changed_source = source.replace("\"QueueCommand\"", "\"QueueCommandChanged\"");
        let changed = generate(&temp.path().join("changed"), &changed_source).unwrap();
        // The same snapshot comparison as --check must fail for this isolated
        // supported upstream method change, then succeed after regeneration.
        assert_eq!(differences(&changed, &original), ["methods.ts: differs"]);
        assert!(differences(&changed, &changed).is_empty());
        let changed = source.replace("pub const QUEUE_COMMAND:", "pub const REMOVED_COMMAND:");
        assert!(
            method_inventory(&changed)
                .unwrap_err()
                .to_string()
                .contains("QUEUE_COMMAND")
        );
    }

    #[test]
    fn snapshot_comparison_detects_changed_missing_and_extra_schema_files() {
        let expected = Snapshot::from([("EngineInfo.ts".into(), b"upstream schema".to_vec())]);
        assert!(differences(&expected, &expected).is_empty());
        assert_eq!(
            differences(&expected, &Snapshot::new()),
            ["EngineInfo.ts: missing"]
        );
        let changed = Snapshot::from([("EngineInfo.ts".into(), b"modified schema".to_vec())]);
        assert_eq!(differences(&expected, &changed), ["EngineInfo.ts: differs"]);
        assert!(!differences(&Snapshot::new(), &expected).is_empty());
    }
}
